Repository Soumyajit2825/Payment_Form, pull requests merged in 2022-10, with the labels that each got.

#2 Added some blue shades of color and edited few line of HTML
  Screenshot2.png
  Screenshot3.png
  index.html
  screenshot1.png
  style_form.css
Labels: good first issue, hacktoberfest, hacktoberfest accepted

#3 Updated Colors and hover effect of the form
  style_form.css
Labels: good first issue, hacktoberfest, hacktoberfest accepted

#12 Done Successfully
  style_form.css
Labels: hacktoberfest, hacktoberfest accepted

#13 change the font
  style_form.css
Labels: hacktoberfest, hacktoberfest accepted

#15 Successfully updated border of the html file
  style_form.css
Labels: hacktoberfest, hacktoberfest accepted

#16 font family change
  index.html
Labels: hacktoberfest, hacktoberfest accepted

#18 Successfully changed the hover effect of html
  style_form.css
Labels: hacktoberfest, hacktoberfest accepted

#19 change the hover effect
  style_form.css
Labels: hacktoberfest, hacktoberfest accepted

#26 Modified the css file
  style_form.css
Labels: hacktoberfest, hacktoberfest accepted

#29 changed the content color
  style_form.css
Labels: hacktoberfest, hacktoberfest accepted

#28 how to contribute section done
  README.md
Labels: hacktoberfest, hacktoberfest accepted

#32 Modified the padding
  style_form.css
Labels: hacktoberfest, hacktoberfest accepted

#33 Update index.html
  index.html
Labels: documentation, hacktoberfest, hacktoberfest accepted

#34 Changed padding
  style_form.css
Labels: hacktoberfest, hacktoberfest accepted

#35 Modified font size
  style_form.css
Labels: hacktoberfest, hacktoberfest accepted

#36 Changed font
  style_form.css
Labels: hacktoberfest, hacktoberfest accepted

#41 colour-scheme change to make more eyefriendly
  style_form.css
Labels: hacktoberfest, hacktoberfest accepted
